config/routes.rb
Rails.application.routes.draw do

  resources :car_rents
  resources :cars
  resources :car_models
  resources :car_manufacturers
  resources :car_producers
  resources :customers
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car_manufacturer.rb
class CarManufacturer < ApplicationRecord
end

app/controllers/car_manufacturers_controller.rb
class CarManufacturersController < ApplicationController
  before_action :set_car_manufacturer, only: [:show, :edit, :update, :destroy]

  # GET /car_manufacturers
  # GET /car_manufacturers.json
  def index
    @car_manufacturers = CarManufacturer.all
  end

  # GET /car_manufacturers/1
  # GET /car_manufacturers/1.json
  def show
  end

  # GET /car_manufacturers/new
  def new
    @car_manufacturer = CarManufacturer.new
  end

  # GET /car_manufacturers/1/edit
  def edit
  end

  # POST /car_manufacturers
  # POST /car_manufacturers.json
  def create
    @car_manufacturer = CarManufacturer.new(car_manufacturer_params)

    respond_to do |format|
      if @car_manufacturer.save
        format.html { redirect_to @car_manufacturer, notice: 'Car manufacturer was successfully created.' }
        format.json { render :show, status: :created, location: @car_manufacturer }
      else
        format.html { render :new }
        format.json { render json: @car_manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_manufacturers/1
  # PATCH/PUT /car_manufacturers/1.json
  def update
    respond_to do |format|
      if @car_manufacturer.update(car_manufacturer_params)
        format.html { redirect_to @car_manufacturer, notice: 'Car manufacturer was successfully updated.' }
        format.json { render :show, status: :ok, location: @car_manufacturer }
      else
        format.html { render :edit }
        format.json { render json: @car_manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_manufacturers/1
  # DELETE /car_manufacturers/1.json
  def destroy
    @car_manufacturer.destroy
    respond_to do |format|
      format.html { redirect_to car_manufacturers_url, notice: 'Car manufacturer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_manufacturer
      @car_manufacturer = CarManufacturer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_manufacturer_params
      params.require(:car_manufacturer).permit(:name)
    end
end

app/helpers/car_manufacturers_helper.rb
module CarManufacturersHelper
end

app/views/car_manufacturers/_form.html.slim
= simple_form_for(@car_manufacturer) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/car_manufacturers/edit.html.slim
h1 Editing car_manufacturer

== render 'form'

= link_to 'Show', @car_manufacturer
'|
= link_to 'Back', car_manufacturers_path

app/views/car_manufacturers/index.html.slim
h1 Listing car_manufacturers

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @car_manufacturers.each do |car_manufacturer|
      tr
        td = car_manufacturer.name
        td = link_to 'Show', car_manufacturer
        td = link_to 'Edit', edit_car_manufacturer_path(car_manufacturer)
        td = link_to 'Destroy', car_manufacturer, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Car manufacturer', new_car_manufacturer_path

app/views/car_manufacturers/new.html.slim
h1 New car_manufacturer

== render 'form'

= link_to 'Back', car_manufacturers_path

app/views/car_manufacturers/show.html.slim
p#notice = notice

p
  strong Name:
  = @car_manufacturer.name

= link_to 'Edit', edit_car_manufacturer_path(@car_manufacturer)
'|
= link_to 'Back', car_manufacturers_path