config/routes.rb
Rails.application.routes.draw do

  resources :car_rents
  resources :cars
  resources :car_models
  resources :car_manufacturers
  resources :car_producers
  resources :customers
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car_rent.rb
class CarRent < ApplicationRecord
  belongs_to :customer
  belongs_to :car
end

app/controllers/car_rents_controller.rb
class CarRentsController < ApplicationController
  before_action :set_car_rent, only: [:show, :edit, :update, :destroy]

  # GET /car_rents
  # GET /car_rents.json
  def index
    @car_rents = CarRent.all
  end

  # GET /car_rents/1
  # GET /car_rents/1.json
  def show
  end

  # GET /car_rents/new
  def new
    @car_rent = CarRent.new
  end

  # GET /car_rents/1/edit
  def edit
  end

  # POST /car_rents
  # POST /car_rents.json
  def create
    @car_rent = CarRent.new(car_rent_params)

    respond_to do |format|
      if @car_rent.save
        format.html { redirect_to @car_rent, notice: 'Car rent was successfully created.' }
        format.json { render :show, status: :created, location: @car_rent }
      else
        format.html { render :new }
        format.json { render json: @car_rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_rents/1
  # PATCH/PUT /car_rents/1.json
  def update
    respond_to do |format|
      if @car_rent.update(car_rent_params)
        format.html { redirect_to @car_rent, notice: 'Car rent was successfully updated.' }
        format.json { render :show, status: :ok, location: @car_rent }
      else
        format.html { render :edit }
        format.json { render json: @car_rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_rents/1
  # DELETE /car_rents/1.json
  def destroy
    @car_rent.destroy
    respond_to do |format|
      format.html { redirect_to car_rents_url, notice: 'Car rent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_rent
      @car_rent = CarRent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_rent_params
      params.require(:car_rent).permit(:date_from, :date_to, :price, :customer_id, :car_id)
    end
end

app/helpers/car_rents_helper.rb
module CarRentsHelper
end

app/views/car_rents/_form.html.slim
= simple_form_for(@car_rent) do |f|
  = f.error_notification

  .form-inputs
    = f.input :date_from
    = f.input :date_to
    = f.input :price
    = f.association :customer
    = f.association :car

  .form-actions
    = f.button :submit

app/views/car_rents/edit.html.slim
h1 Editing car_rent

== render 'form'

= link_to 'Show', @car_rent
'|
= link_to 'Back', car_rents_path

app/views/car_rents/index.html.slim
h1 Listing car_rents

table
  thead
    tr
      th Date from
      th Date to
      th Price
      th Customer
      th Car
      th
      th
      th

  tbody
    - @car_rents.each do |car_rent|
      tr
        td = car_rent.date_from
        td = car_rent.date_to
        td = car_rent.price
        td = car_rent.customer
        td = car_rent.car
        td = link_to 'Show', car_rent
        td = link_to 'Edit', edit_car_rent_path(car_rent)
        td = link_to 'Destroy', car_rent, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Car rent', new_car_rent_path

app/views/car_rents/new.html.slim
h1 New car_rent

== render 'form'

= link_to 'Back', car_rents_path

app/views/car_rents/show.html.slim
p#notice = notice

p
  strong Date from:
  = @car_rent.date_from
p
  strong Date to:
  = @car_rent.date_to
p
  strong Price:
  = @car_rent.price
p
  strong Customer:
  = @car_rent.customer
p
  strong Car:
  = @car_rent.car

= link_to 'Edit', edit_car_rent_path(@car_rent)
'|
= link_to 'Back', car_rents_path