config/routes.rb
Rails.application.routes.draw do

  resources :car_rents
  resources :cars
  resources :car_models
  resources :car_manufacturers
  resources :car_producers
  resources :customers
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :car_model
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:car_model_id, :plate, :price)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.slim
= simple_form_for(@car) do |f|
  = f.error_notification

  .form-inputs
    = f.association :car_model
    = f.input :plate
    = f.input :price

  .form-actions
    = f.button :submit

app/views/cars/edit.html.slim
h1 Editing car

== render 'form'

= link_to 'Show', @car
'|
= link_to 'Back', cars_path

app/views/cars/index.html.slim
h1 Listing cars

table
  thead
    tr
      th Car model
      th Plate
      th Price
      th
      th
      th

  tbody
    - @cars.each do |car|
      tr
        td = "#{car.car_model.car_manufacturer.name} #{car.car_model.name}"
        td = car.plate
        td = car.price
        td = link_to 'Show', car
        td = link_to 'Edit', edit_car_path(car)
        td = link_to 'Destroy', car, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Car', new_car_path

app/views/cars/new.html.slim
h1 New car

== render 'form'

= link_to 'Back', cars_path

app/views/cars/show.html.slim
p#notice = notice

p
  strong Car model:
  = "#{@car.car_model.car_manufacturer.name} #{@car.car_model.name}"
p
  strong Plate:
  = @car.plate
p
  strong Price:
  = @car.price

= link_to 'Edit', edit_car_path(@car)
'|
= link_to 'Back', cars_path